name: Centos7 CI (deps. compilation)

on:
  push:
    branches:
      - release/*
      - develop

jobs:

  build:

    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:

    - name: Install libraries
      run: |
           yum install -y epel-release
           yum install -y git

