name: Build the singularity contianer

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@2

    - name: Build contianer
      uses: ifurther/actions@master

