name: Build the singularity contianer

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.TOKEN }}

    - name: Build contianer
      uses: ifurther/actions@master
      with:
        action-command: build
    
    - name: Build contianer
      uses: ifurther/actions@master
      with:
        action-command: run


